apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.user1: apiKey, login
  accounts.user2: apiKey
  accounts.user3: login
  accounts.user4: apiKey, login
  # disables user. User is enabled by default
  accounts.user4.enabled: "false"