# active用(Blue)Service
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  selector:
    app: rollout-bluegreen
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
